name: CI/CD Deploy to Kubernetes
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      DOCKER_REGISTRY_INTERNAL: ${{ secrets.DOCKER_REGISTRY_INTERNAL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_EXTERNAL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: build and push docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_REGISTRY_EXTERNAL }}/${{ secrets.docker_username }}/streamlit-app:latest .
      #     docker push ${{ secrets.DOCKER_REGISTRY_EXTERNAL }}/${{ secrets.docker_username }}/streamlit-app:latest

      - name: Set up K8S context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          context: ${{ secrets.K8S_CONTEXT }}
        id: setcontext


      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{secrets.K8S_NAMESPACE}}
          imagepullsecrets: |
            ${{env.K8S_IMAGE_PULL_SECRETS}}
          manifests: |
            k8s-dev-deployment.yml
          
        