name: CI/CD Deploy to Kubernetes
env:
  DOCKER_REGISTRY_INTERNAL: ${{ secrets.DOCKER_REGISTRY_INTERNAL }}
  DOCKER_REGISTRY_EXTERNAL: ${{ secrets.DOCKER_REGISTRY_EXTERNAL }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  K8S_IMAGE_PULL_SECRETS: ${{ secrets.K8S_IMAGE_PULL_SECRETS }}
  K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_EXTERNAL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube || \
          echo "${{ env.K8S_CONFIG }}" > $HOME/.kube/config

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ env.DOCKER_REGISTRY_EXTERNAL }}/${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .
      #     docker push ${{ env.DOCKER_REGISTRY_EXTERNAL }}/${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          imagepullsecrets: |
            ${{env.K8S_IMAGE_PULL_SECRETS}}
          manifests: |
            k8s-dev-deployment.yml
        