name: CI/CD Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.K8S_CONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/streamlit-app streamlit-app=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest --namespace=${{ secrets.K8S_PROJECT_NAMESPACE }} || \
          kubectl create deployment streamlit-app --image=${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest --namespace=${{ secrets.K8S_PROJECT_NAMESPACE }}
          kubectl expose deployment streamlit-app --type=LoadBalancer --port=8501 --name=streamlit-service --namespace=${{ secrets.K8S_PROJECT_NAMESPACE }} || true